### PR TITLE
Change to machine-readable format

### PR DESCRIPTION
**Pull request by AristoChen**
Hi,

This PR is for #21 

For `categories`, I am not sure what should I put, so I put `linter` currently

For `tags`, all of them were edited manually, so if there is anything that I did’nt make it right, please let me know

For `licenses`, I put `MIT License` by default, then I browse all the link to check whether their website indicate which license they are using, if they do mention about the license, then I manually edit the `.yml` file.

For `types`, I put `cli` by default

If there is anything that I didn’t make it right, please let me know

### CODE REVIEW

**Comment by AristoChen** [comment]
Just found that I was not using the latest render code from `static-anaylsis`, will fix it later

**Comment by AristoChen** [comment]
I update the `Makefile` and `tags.yml`, and the `SAST` is changed to `DAST`

I am wondering if it makes sense to create another repo only for the render code, and it will be used to render `README.md` for both `static-analysis` and `dynamic-analysis`, otherwise we have to keep the render code in both repo same with each other

**Comment by mre** [comment]
Thanks for the impressive first step @AristoChen.

> For categories, I am not sure what should I put, so I put linter currently

Yeah guess that's fine for now. I think we should go through the [list on Wikipedia](https://en.wikipedia.org/wiki/Dynamic_program_analysis) and classify the tools accordingly. Categories that come to mind:

* concurrency
* security
* memory

There's more and the ones I mentioned are debatable, but I think it's a good start.
We also have the `security` tag, but I think that should rather be a category in the case of dynamic analysis. Any objections?

> For tags, all of them were edited manually, so if there is anything that I didn't make it right, please let me know

Looks good from what I can tell.

> For licenses, I put MIT License by default, then I browse all the link to check whether their website indicate which license they are using, if they do mention about the license, then I manually edit the .yml file.

Also looks good.

> For types, I put cli by default

Yeah, makes sense.

> I am wondering if it makes sense to create another repo only for the render code, and it will be used to render README.md for both static-analysis and dynamic-analysis, otherwise we have to keep the render code in both repo same with each other

True. We could move it into a separate repo and create a Github action from it. The disadvantage would be that people can't use it to test their changes locally, but I think eventually we need a better answer for that anyway.

From my side this is good to merge. @AristoChen do you want to change anything before?

**Comment by AristoChen** [comment]
> Any objections?

Good for me

> True. We could move it into a separate repo and create a Github action from it. The disadvantage would be that people can't use it to test their changes locally, but I think eventually we need a better answer for that anyway.

Yup that will be inconvenient if people want to test locally, maybe we can use `submodule` in both `static-analysis` and `dynamic-analysis`?

>  do you want to change anything before?

Nothing from my side currently

**Comment by mre** [comment]
> Yup that will be inconvenient if people want to test locally, maybe we can use submodule in both static-analysis and dynamic-analysis?

Not a huge fan of submodules tbh. `git submodule init` caused quite a bit of confusion in some prior projects. :/ Personally I'd go with the Github action route and maybe work on a better way to add and edit tools. Maybe through the website eventually or with a little scaffolder. 🤷

**Pull request merged**
