### PR TITLE
Add icontract in Python

### PR DESCRIPTION
**Pull request by mristin**

### CODE REVIEW

**Comment by mristin** [comment]
(I made this update with GitHub editor. The last line automatically changed and I have no idea why.)

**Comment by mre** [comment]
Very nice library.
Can you revert the change to the readme and add a `yml` file to `data/tools`? The readme is actually just a rendered version of that folder. We do that for automatic formatting and to be able to render the data in other formats in the future. 😉

**Comment by mristin** [comment]
Hi @mre ,
I'm a bit overwhelmed with the format. Could you please tell me what `categories` and `types` I should assign? All the other tools are categorized as `linter` and `cli` types.

(pyicontract-lint is indeed a linter, so I can add it as well, but icontract is a library.)

**Comment by mre** [comment]
Fair point. We haven't encountered that scenario yet. Feel free to use `linter` as the category and `library` as a type for icontract then. If there are CI errors with that new type I will fix them.

**Comment by mristin** [comment]
@mre please let me know if this is OK now? I don't see on my side any CI running. You will test the rendering then?

**Comment by mre** [comment]
Hey @mristin,
your entry looks great. Realized that the CI was not triggered because... well... it didn't exist. Thought we copied it over from [static-analysis](https://github.com/analysis-tools-dev/static-analysis), but we didn't.
Fixed that now and made a few changes to trigger a rebuild. Looks fine now.
Merging and thanks for your contribution. 😊

**Pull request merged**
