### PR TITLE
Create crosshair.yml

### PR DESCRIPTION
**Pull request by pschanely**
Hi! CrossHair probably meets the bar for inclusion here?
Hopefully I got the PR right. (didn't try `make render` myself...)

### CODE REVIEW

**Comment by mre** [comment]
Thanks for the PR; much appreciated!

> CrossHair probably meets the bar for inclusion here?

Barely. 😆 Just kidding, looks like it's super popular.

> Hopefully I got the PR right. 

Format looks great. The description in the repo describes it as a "static analysis tool for Python" while this project is for dynamic analysis tools. Would you say it's a better fit for https://github.com/analysis-tools-dev/static-analysis? I'm fine with either.

**Comment by pschanely** [comment]
I have been struggling with this question! It's a bit confusing for CrossHair because it has aspects that make it look like either. (I'm the primary maintainer, and have just now removed the "static" word in the summary to ... heh ... avoid the discussion):

Arguments for "static analysis":
* You can use it like a static analysis tool (as an IDE plug-in for instance).
* In some cases, CrossHair verifies properties *over all* inputs, making it act like a type checker or verification tool.

Arguments for "dynamic analysis":
* The process is "undecidable" in a CS sense; you can't always (or even usually) run it and get a definitive answer about whether a property holds or not.
* It really does "execute" your code. (in a *symbolic execution* sense, though, not with normal Python inputs)

I am guessing that the dynamic analysis section is the right place, because we have other symbolic execution tools here which have a lot of similarities to CrossHair; "KLEE", is a good example.

**Comment by mre** [comment]
Perfect. Thanks for the thorough explanation. Merging. 😊

**Comment by mre** [comment]
Soon the dynamic analysis tools will also be indexed on analysis-tools.dev. 😉

**Pull request merged**
